spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        default_schema: budget_schema
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000